import { ECandidateStatuses } from "entities/candidate";

export const candidates = () => {
    return [
        {
            candidateId: 1,
            candidateFio: "Иван Иванов",
            candidateEmail: "ivan.ivanov@example.com",
            candidatePhone: "+79123456789",
            candidateSalary: 60000,
            candidatePosition: "Разработчик ПО",
            candidateExperience: 5,
            candidateCompanies: ["Компания A", "Компания B", "Компания C"],
            candidateCitizen: "Россия",
            candidateCity: "Москва",
            candidateAge: 30,
            candidateSkills: ["Java", "Spring", "Hibernate"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 2,
            candidateFio: "Мария Петрова",
            candidateEmail: "maria.petrova@example.com",
            candidatePhone: "+79123456788",
            candidateSalary: 70000,
            candidatePosition: "Аналитик данных",
            candidateExperience: 4,
            candidateCompanies: ["Компания X", "Компания Y"],
            candidateCitizen: "Россия",
            candidateCity: "Санкт-Петербург",
            candidateAge: 28,
            candidateSkills: ["SQL", "Python", "Анализ данных"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 3,
            candidateFio: "Алексей Сидоров",
            candidateEmail: "alex.sidorov@example.com",
            candidatePhone: "+79123456787",
            candidateSalary: 55000,
            candidatePosition: "Тестировщик ПО",
            candidateExperience: 3,
            candidateCompanies: ["Компания P", "Компания Q"],
            candidateCitizen: "Россия",
            candidateCity: "Екатеринбург",
            candidateAge: 26,
            candidateSkills: ["Selenium", "Jira", "Тест-дизайн"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 4,
            candidateFio: "Елена Козлова",
            candidateEmail: "elena.kozlova@example.com",
            candidatePhone: "+79123456786",
            candidateSalary: 75000,
            candidatePosition: "Продуктовый менеджер",
            candidateExperience: 6,
            candidateCompanies: ["Компания M", "Компания N"],
            candidateCitizen: "Россия",
            candidateCity: "Казань",
            candidateAge: 34,
            candidateSkills: ["Product Management", "Agile", "Market Research"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 5,
            candidateFio: "Павел Никитин",
            candidateEmail: "pavel.nikitin@example.com",
            candidatePhone: "+79123456785",
            candidateSalary: 62000,
            candidatePosition: "DevOps инженер",
            candidateExperience: 4,
            candidateCompanies: ["Компания R", "Компания S"],
            candidateCitizen: "Россия",
            candidateCity: "Новосибирск",
            candidateAge: 29,
            candidateSkills: ["Docker", "Kubernetes", "CI/CD"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 6,
            candidateFio: "Анна Смирнова",
            candidateEmail: "anna.smirnova@example.com",
            candidatePhone: "+79123456784",
            candidateSalary: 68000,
            candidatePosition: "UX/UI дизайнер",
            candidateExperience: 5,
            candidateCompanies: ["Компания K", "Компания L"],
            candidateCitizen: "Россия",
            candidateCity: "Самара",
            candidateAge: 31,
            candidateSkills: ["Adobe XD", "Figma", "User Research"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 7,
            candidateFio: "Денис Зайцев",
            candidateEmail: "denis.zaytsev@example.com",
            candidatePhone: "+79123456783",
            candidateSalary: 58000,
            candidatePosition: "Системный администратор",
            candidateExperience: 4,
            candidateCompanies: ["Компания D", "Компания E"],
            candidateCitizen: "Россия",
            candidateCity: "Красноярск",
            candidateAge: 27,
            candidateSkills: ["Linux", "Networking", "Troubleshooting"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 8,
            candidateFio: "Татьяна Иванова",
            candidateEmail: "tatyana.ivanova@example.com",
            candidatePhone: "+79123456782",
            candidateSalary: 70000,
            candidatePosition: "Data Scientist",
            candidateExperience: 4,
            candidateCompanies: ["Компания F", "Компания G"],
            candidateCitizen: "Россия",
            candidateCity: "Ростов-на-Дону",
            candidateAge: 32,
            candidateSkills: ["Machine Learning", "Python", "Data Modeling"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.awaiting
        },
        {
            candidateId: 9,
            candidateFio: "Ирина Сергеева",
            candidateEmail: "irina.sergeeva@example.com",
            candidatePhone: "+79123456781",
            candidateSalary: 54000,
            candidatePosition: "HR-специалист",
            candidateExperience: 3,
            candidateCompanies: ["Компания H", "Компания I"],
            candidateCitizen: "Россия",
            candidateCity: "Владивосток",
            candidateAge: 28,
            candidateSkills: ["Recruitment", "Employee Relations", "HRIS"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.accept
        },
        {
            candidateId: 10,
            candidateFio: "Сергей Павлов",
            candidateEmail: "sergey.pavlov@example.com",
            candidatePhone: "+79123456780",
            candidateSalary: 73000,
            candidatePosition: "IT директор",
            candidateExperience: 8,
            candidateCompanies: ["Компания J", "Компания T"],
            candidateCitizen: "Россия",
            candidateCity: "Краснодар",
            candidateAge: 38,
            candidateSkills: ["IT Strategy", "Leadership", "Budget Planning"],
            candidateInitiator: 1,
            candidateStatus: ECandidateStatuses.rejected
        }
    ];
};